import { ref } from "vue";

export const nomesPessoas = ref([
  { label: "Jefferson" },
  { label: "Vallie" },
  { label: "Darren" },
  { label: "Theodora" },
  { label: "Ronaldo" },
  { label: "Elijah" },
  { label: "Kristy" },
  { label: "Alessia" },
  { label: "Letitia" },
  { label: "Ashlynn" },
  { label: "Ulices" },
  { label: "Cleora" },
  { label: "Selina" },
  { label: "Braulio" },
  { label: "Sydnie" },
  { label: "Bertram" },
  { label: "Marianna" },
  { label: "Brett" },
  { label: "Burdette" },
  { label: "Hortense" },
  { label: "Wilburn" },
  { label: "Daisy" },
  { label: "Jazmyn" },
  { label: "Stanton" },
  { label: "Linwood" },
  { label: "Gaylord" },
  { label: "Elyse" },
  { label: "Kiel" },
  { label: "Salvador" },
  { label: "Leonora" },
  { label: "Palma" },
  { label: "Ofelia" },
  { label: "Katrine" },
  { label: "Dallas" },
  { label: "Otha" },
  { label: "Ellie" },
  { label: "Reina" },
  { label: "Meda" },
  { label: "Camilla" },
  { label: "Maye" },
  { label: "Curt" },
  { label: "Harmony" },
  { label: "Helga" },
  { label: "Leo" },
  { label: "Rowena" },
  { label: "Eleanore" },
  { label: "Myra" },
  { label: "Ryley" },
  { label: "Jazmin" },
  { label: "Kitty" },
  { label: "Jennyfer" },
  { label: "Pierre" },
  { label: "Irma" },
  { label: "Duncan" },
  { label: "Aletha" },
  { label: "Florida" },
  { label: "Hilario" },
  { label: "Norris" },
  { label: "Emile" },
  { label: "Shane" },
  { label: "Nadia" },
  { label: "Larry" },
  { label: "Sidney" },
  { label: "Duncan" },
  { label: "Bettie" },
  { label: "Pattie" },
  { label: "Vida" },
  { label: "Ephraim" },
  { label: "Darwin" },
  { label: "Santiago" },
  { label: "Maye" },
  { label: "Mariana" },
  { label: "Cleo" },
  { label: "Jennings" },
  { label: "Nestor" },
  { label: "Emmy" },
  { label: "Adonis" },
  { label: "Selmer" },
  { label: "Phyllis" },
  { label: "Robb" },
  { label: "Alvis" },
  { label: "Tamara" },
  { label: "Antonina" },
  { label: "Mylene" },
  { label: "Keanu" },
  { label: "Larue" },
  { label: "Myrtice" },
  { label: "Floy" },
  { label: "Alexandre" },
  { label: "Sydnee" },
  { label: "Arnulfo" },
  { label: "Patricia" },
  { label: "Monte" },
  { label: "Austin" },
  { label: "Mavis" },
  { label: "Madie" },
  { label: "Emmy" },
  { label: "Freida" },
  { label: "Yessenia" },
  { label: "Glenna" },
  { label: "Andreanne" },
  { label: "Demarcus" },
  { label: "Jacynthe" },
  { label: "Lydia" },
  { label: "Nicolas" },
  { label: "Malika" },
  { label: "Greta" },
  { label: "Eileen" },
  { label: "Kay" },
  { label: "Dillan" },
  { label: "Zander" },
  { label: "Hilton" },
  { label: "Mina" },
  { label: "Lexi" },
  { label: "Else" },
  { label: "Eda" },
  { label: "Felton" },
  { label: "Janelle" },
  { label: "Timmothy" },
  { label: "Prince" },
  { label: "Parker" },
  { label: "Henri" },
  { label: "Danika" },
  { label: "Jakayla" },
  { label: "Annie" },
  { label: "Emil" },
  { label: "Christophe" },
  { label: "Dominic" },
  { label: "Aurore" },
  { label: "Shakira" },
  { label: "Naomie" },
  { label: "Jewel" },
  { label: "Johanna" },
  { label: "Armani" },
  { label: "Braeden" },
  { label: "Uriah" },
  { label: "Stephon" },
  { label: "Lila" },
  { label: "Lisandro" },
  { label: "Ines" },
  { label: "Angelo" },
  { label: "Jay" },
  { label: "Adolfo" },
  { label: "Abdul" },
  { label: "Carleton" },
  { label: "Ronaldo" },
  { label: "Irma" },
  { label: "Alberto" },
  { label: "Jimmie" },
  { label: "Marguerite" },
  { label: "Joesph" },
  { label: "Elena" },
  { label: "Manuel" },
  { label: "Jonathan" },
  { label: "Mariah" },
  { label: "Joe" },
  { label: "Tessie" },
  { label: "Hayley" },
  { label: "Patrick" },
  { label: "Sarina" },
  { label: "Orlando" },
  { label: "Richmond" },
  { label: "Vivienne" },
  { label: "Karson" },
  { label: "Maye" },
  { label: "Raegan" },
  { label: "Noelia" },
  { label: "Tiara" },
  { label: "Penelope" },
  { label: "Jesse" },
  { label: "Furman" },
  { label: "Christine" },
  { label: "Lia" },
  { label: "Tyrique" },
  { label: "Cody" },
  { label: "Junius" },
  { label: "Birdie" },
  { label: "Bailey" },
  { label: "Margarette" },
  { label: "Charley" },
  { label: "Elbert" },
  { label: "Camden" },
  { label: "Ross" },
  { label: "Hailie" },
  { label: "Jessie" },
  { label: "Louisa" },
  { label: "Miguel" },
  { label: "Clotilde" },
  { label: "River" },
  { label: "Jacinto" },
  { label: "Gregory" },
  { label: "Malachi" },
  { label: "Rylee" },
  { label: "Keegan" },
  { label: "Veda" },
  { label: "Frederick" },
  { label: "Malika" },
  { label: "Dorthy" },
  { label: "Consuelo" },
  { label: "Melisa" },
  { label: "Zelma" },
  { label: "Christophe" },
  { label: "Brendon" },
  { label: "Lonnie" },
  { label: "Hermann" },
  { label: "Gino" },
  { label: "Rafaela" },
  { label: "Sandrine" },
  { label: "Santino" },
  { label: "Sabrina" },
  { label: "Margie" },
  { label: "Roxanne" },
  { label: "Ted" },
  { label: "Ida" },
  { label: "Katherine" },
  { label: "Lurline" },
  { label: "Skylar" },
  { label: "Eleanore" },
  { label: "Merle" },
  { label: "Jamarcus" },
  { label: "Veda" },
  { label: "Mckenna" },
  { label: "Berry" },
  { label: "Martin" },
  { label: "Rahul" },
  { label: "Dan" },
  { label: "Jarod" },
  { label: "Tillman" },
  { label: "Laurie" },
  { label: "Mariam" },
  { label: "Walter" },
  { label: "Alexzander" },
]);

export const empresas = ref([
  {
    label: "Tech Raiz Ltda",
    value: "TR",
    departamentos: [
      {
        label: "Desenvolvimento",
        value: "DEV",
        equipes: [
          {
            label: "Backend",
            value: "BE",
            membros: [
              { label: "João", value: "DEV-BE-01" },
              { label: "Maria", value: "DEV-BE-02" },
            ],
          },
          {
            label: "Frontend",
            value: "FE",
            membros: [
              { label: "Carlos", value: "DEV-FE-01" },
              { label: "Ana", value: "DEV-FE-02" },
            ],
          },
        ],
      },
    ],
  },
  {
    label: "Tech Raiz Ltda",
    value: "TR",
    departamentos: [
      {
        label: "Desenvolvimento",
        value: "DEV",
        equipes: [
          {
            label: "Backend",
            value: "BE",
            membros: [
              { label: "João", value: "DEV-BE-01" },
              { label: "Maria", value: "DEV-BE-02" },
            ],
          },
          {
            label: "Frontend",
            value: "FE",
            membros: [
              { label: "Carlos", value: "DEV-FE-01" },
              { label: "Ana", value: "DEV-FE-02" },
            ],
          },
        ],
      },
    ],
  },
]);